boot disk: EFI/GPT supported
Signed-off-by: Conke Hu <conke.hu@maxwit.com>

diff --git a/boot-disk/createinstallmedia b/boot-disk/createinstallmedia
--- a/boot-disk/createinstallmedia
+++ b/boot-disk/createinstallmedia
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if [ $UID != 0 ]; then
+	echo "must run as root!"
+	exit 1
+fi
+
 if [ $# = 1 ]; then
 	root=$1
 	repo=$1/iso
@@ -63,6 +68,22 @@ if [ $? = 0 ]; then
 else
     grub_cmd="grub-install"
     grub_cfg="$boot/grub/grub.cfg"
+fi
+
+table=`parted $disk print | awk '{if ($1 == "Partition") {print $3}}'`
+if [ $table = "gpt" ]; then
+	grub_cmd="$grub_cmd --target=x86_64-efi"
+
+	esp=`parted $disk print | awk '{if ($1 >= 1 && $1 <=128 && $8 == "esp") {print $1} }'`
+	if [ -z $esp ]; then
+		echo "ESP partition not found!"
+		exit 1
+	fi
+	umount $disk$esp
+	mkdir -p $boot/efi
+	mount $disk$esp $boot/efi
+else
+	grub_cmd="$grub_cmd --target=i386-pc"
 fi
 
 $grub_cmd --boot-directory=$boot $disk
